# 1. BUILD STAGE: Node를 사용하여 React 앱 빌드
FROM node:20-slim as build

WORKDIR /app

# 패키지 파일 복사 및 종속성 설치 (캐시 최적화)
COPY frontend/package*.json ./
RUN npm install

# 소스 코드 복사 및 빌드
COPY frontend/ .

# 빌드 실행: 빌드 결과물은 /app/build 폴더에 생성됩니다.
RUN npm run build

# 2. RUN STAGE: Nginx 컨테이너에 빌드 결과 복사
FROM nginx:stable-alpine as production

# Nginx 설정 파일 복사
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# 빌드 스테이지에서 생성된 정적 파일을 Nginx 서빙 경로로 복사
COPY --from=build /app/build /usr/share/nginx/html
